<?xml version="1.0" encoding="utf-8"?><Database Name="PharmaMev" Class="PharmaLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pc;Initial Catalog=PharmaMev;Integrated Security=True" SettingsObjectName="PharmaMev.Properties.Settings" SettingsPropertyName="PharmaMevConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="ID_Groups" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Group_Product" Member="Products" ThisKey="ID_Groups" OtherKey="ID_Groups" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID_Customer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomerPhone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Caule" Member="Caules">
    <Type Name="Caule">
      <Column Name="ID_Caule" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CauleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ID_Product" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BarCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Units" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SubQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BiggerUnit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EX_Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Groups" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Group_Product" Member="Group" ThisKey="ID_Groups" OtherKey="ID_Groups" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuysAction" Member="BuysActions">
    <Type Name="BuysAction">
      <Column Name="ID_BuyAction" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Buy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantit_BuysAction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EX_Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="totatCost" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SalesAction" Member="SalesActions">
    <Type Name="SalesAction">
      <Column Name="ID_SaleAction" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Sale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity_SaleAction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SalePrecentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buys" Member="Buys">
    <Type Name="Buy">
      <Column Name="ID_Buy" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateBuy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BuyCost" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ID_Caule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="ID_Product" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Defective" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="User_Psw" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SalePermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuyPermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProductsPermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReportsPermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsersPermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SettingPermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoragePermissions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sales" Member="Sales">
    <Type Name="Sale">
      <Column Name="ID_Sale" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SaleDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="paid" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ID_Customer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>